let types = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",
  FILTER_BY_CATEGORY_PRODUCT: "FILTER_BY_CATEGORY_PRODUCT",
  FILTER_BY_SUB_CATEGORY_PRODUCT: "FILTER_BY_SUB_CATEGORY_PRODUCT"
};

export { types };